name: Publish Helm Chart

on:
  push:
    paths:
      - 'faktura-statistik/**'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Enable OCI support
        run: export HELM_EXPERIMENTAL_OCI=1

      - name: Package Helm Chart
        working-directory: ./faktura-statistik
        run: helm package . --version ${GITHUB_RUN_NUMBER}

      - name: Login to GHCR
        run: helm registry login ghcr.io \
          --username ${{ github.actor }} \
          --password ${{ secrets.GITHUB_TOKEN }}

      - name: Push OCI Chart
        env:
          HELM_EXPERIMENTAL_OCI: 1
        run: |
          VERSION=${GITHUB_RUN_NUMBER}
          helm chart save faktura-statistik-${VERSION}.tgz \
            oci://ghcr.io/ldilba/faktura-statistik
          helm chart push oci://ghcr.io/ldilba/faktura-statistik:${VERSION}
