# .github/workflows/publish-helm-chart.yml
name: Publish Helm Chart

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'faktura-statistik-charts/**'
      - '.github/workflows/**'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Code auschecken
      - uses: actions/checkout@v3

      # Helm bequem installieren
      - uses: azure/setup-helm@v4      # lädt standardmäßig die neueste Stable
        # optional festpinnen:
        # with:
        #   version: v3.12.0

      # Gegen GHCR authentifizieren
      - name: Login to GHCR
        run: |
          helm registry login ghcr.io \
            --username "${{ github.actor }}" \
            --password "${{ secrets.GITHUB_TOKEN }}"

      # Chart packen & pushen (Variante 2)
      - name: Package & Push Helm Chart
        env:
          VERSION: ${{ github.run_number }}
        run: |
          helm package ./faktura-statistik-charts --version "$VERSION"
          helm push "faktura-statistik-$VERSION.tgz" \
            oci://ghcr.io/ldilba/faktura-statistik/charts
