# .github/workflows/publish-helm-chart.yml
name: Publish Helm Chart

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'faktura-statistik/**'
      - '.github/workflows/**'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      HELM_EXPERIMENTAL_OCI: 1   # ab Helm ≥3.8 optional – kann bleiben

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Helm (v3.12.0)
        run: |
          HELM_VERSION="v3.12.0"
          curl -fsSL https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz \
            -o helm-${HELM_VERSION}-linux-amd64.tar.gz
          tar -xzf helm-${HELM_VERSION}-linux-amd64.tar.gz
          sudo mv linux-amd64/helm /usr/local/bin/helm
          helm version --short

      - name: Login to GHCR
        run: |
          helm registry login ghcr.io \
            --username "${{ github.actor }}" \
            --password "${{ secrets.GITHUB_TOKEN }}"

      - name: Package & Push Helm Chart
        run: |
          VERSION="${GITHUB_RUN_NUMBER}"

          # Chart aus dem Unterordner packen; Artefakt landet im Root
          helm package ./faktura-statistik --version "${VERSION}"

          # OCI-Push (Chart-Name/Version werden aus dem .tgz gelesen)
          helm push "faktura-statistik-${VERSION}.tgz" \
            oci://ghcr.io/ldilba/faktura-statistik
